### ISSUE TITLE
Development failing

### ISSUE THREAD

**Issue by JeanJPNM** [SimonWoodburyForget/mindustry-mods#27]
Missing the dist folder containing the required file in core/src/lib.rs:52:44

**Comment by JeanJPNM** [comment]
Also why would you put a file in dist?
can you put it in a folder that is accessible to the repository?

**Comment by SimonWoodburyForget** [comment]
`dist` is an automatically generated directory, originally used so the page could be rendered statically by GitHub-Pages (pushed to the gh-pages branch). The Python script drops in the data (json), and then the Cargo-Make executes a few commands that copy the static files into it (wasm/js/html/css), so nothing in `dist` needs to be in the repository.
