### ISSUE TITLE
Used pypi packages

### ISSUE THREAD

**Issue by ForestedDev** [SimonWoodburyForget/mindustry-mods#9]
What pypi packages are used for python, need them for testing/learning how some of this works. Also where did you get yaml, pip3 can't collect it.

**Comment by SimonWoodburyForget** [comment]
`PyYaml` is the `yaml` package: https://pypi.org/project/PyYAML/, other packages include:

```
Click==7.0
hjson==3.0.1
Markdown==3.1.1
Jinja2==2.10.3
requests==2.18.4
schedule==0.6.0
humanize==0.5.1
beautifulsoup4==4.8.1
dataclasses==0.7
parsec==3.5
Pillow==6.2.1
PyGithub==1.44.1
python_dateutil==2.8.1
PyYAML==5.2
```

I'll be updating `requirements.txt` with them. Note that some of these may be more or less included with Python.

**Comment by ForestedDev** [comment]
Ok, thank you!
